{
  "name": "TMTumblrSDK",
  "version": "6.1.4",
  "summary": "An unopinionated and flexible library for easily integrating Tumblr data into your iOS or OS X application.",
  "homepage": "https://github.com/StevenGTrapp/TMTumblrSDK.git",
  "source": {
    "git": "https://github.com/StevenGTrapp/TMTumblrSDK.git",
    "tag": "6.1.4"
  },
  "license": {
    "type": "Apache 2.0",
    "file": "LICENSE"
  },
  "authors" : {
    "Kenny Ackerson": "kenny@tumblr.com"
    "Steven G Trapp": "steven@google.com"
  },
  "platforms": {
    "ios": "10.0",
    "osx": "10.12"
  },
  "requires_arc": true,
  "frameworks": [
    "Foundation"
  ],
  "source_files": "Classes/**/*.{h,m}",
  "dependencies": {
  }

}


